// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	model "github.com/h44z/wg-portal/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PlainAuthenticator is an autogenerated mock type for the PlainAuthenticator type
type PlainAuthenticator struct {
	mock.Mock
}

// HashedAuthentication provides a mock function with given fields: userId, hashedPassword
func (_m *PlainAuthenticator) HashedAuthentication(userId model.UserIdentifier, hashedPassword string) error {
	ret := _m.Called(userId, hashedPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.UserIdentifier, string) error); ok {
		r0 = rf(userId, hashedPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaintextAuthentication provides a mock function with given fields: userId, plainPassword
func (_m *PlainAuthenticator) PlaintextAuthentication(userId model.UserIdentifier, plainPassword string) error {
	ret := _m.Called(userId, plainPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.UserIdentifier, string) error); ok {
		r0 = rf(userId, plainPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
